# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Domain Collecting Tool API
  version: "1.0.0"
# the domain of the service
host: localhost:8080
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /api

paths:
  /public/category:
    get:
      summary: Get category list
      tags:
        - public
      responses:
        200:
          description: An object
          schema:
            type: object
            properties:
               success:
                  type: boolean
                  description: .
               sid:
                  type: number
                  description: site id.
               cid:
                  type: number
                  description: category id.
                  
  /admin/site:
    put:
      summary: Add a site with relationship
      parameters:
        - name: country
          in: query
          description: ID of `country` option.
          required: true
          type: number
          format: integer
        - name: site
          in: query
          description: Literal value of `site` option.
          required: true
          type: string
          format: string
      tags:
        - admin
      responses:
        200:
          description: An object
          schema:
            type: object
            properties:
               success:
                  type: boolean
                  description: .
               sid:
                  type: number
                  description: site id.
               cid:
                  type: number
                  description: category id.
    delete:
      summary: Add a site with relationship
      description: |
        
      parameters:
        - name: site
          in: query
          description: ID of `site` option.
          required: true
          type: number
          format: integer
      tags:
        - admin
      responses:
        200:
          description: Success
        500:
          description: Error